baseURL = 'https://geldrausch.github.io/tech-turnaround-daily/'
languageCode = 'en-us'
title = 'Tech Turnaround Daily'
theme = 'terminal'

[params]
  contentTypeName = 'posts'
  themeColor = 'blue'
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[[params.social]]
  name = "rss"
  url = "/index.xml"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Archive"
    url = "/posts"

[outputs]
  home = ["HTML", "RSS"]
